function [] = exportdbquery(data_file)
%exportdbquery() Exports data from file to DB
%   This function exports already parsed data from CME_dataparse.m script
%   to the database.
%   Input:
%       data_file - path to file with data

load(data_file); % import query_rows variable
conn=database('market_data','admin','uwai7Rai','Vendor','PostgreSQL','Server','192.168.9.1');
tablename='daily_price_staging';
colnames={...
    'data_vendor_name',...
    'exchange_symbol',...
    'vendor_symbol',...
    'complete_symbol',...
    'contract_month',...
    'price_date',...
    'open_price',...
    'high_price',...
    'low_price',...
    'last_price',...
    'settle',...
    'volume',...
    'open_interest'};
datainsert(conn,tablename,colnames,query_rows);

%% Copying data from staging table to target table
% We cant copy data directly from matlab to target table because there are some
% issues with conversion from double to numeric(19,4) format.
% First we need to convert matlab double to postgres double and then
% postgres double to postgres numeric(19,4).
sqlquery=...
    'INSERT INTO daily_price(data_vendor_name,exchange_symbol,vendor_symbol,complete_symbol,contract_month,price_date,open_price,high_price,low_price,last_price,settle,volume,open_interest) SELECT data_vendor_name,exchange_symbol,vendor_symbol,complete_symbol,contract_month,price_date,open_price,high_price,low_price,last_price,settle,volume,open_interest FROM daily_price_staging;';
exec(conn,sqlquery);
exec(conn,'TRUNCATE daily_price_staging');
close(conn);
end

